### PR TITLE
created

### PR DESCRIPTION
**Pull request by 510617114040**

### CODE REVIEW

**Comment by BOOPATHI-COTPOT** [comment]
do a fresh clone, remove this Session_01.ipynb and rename this Session_01_workbook.ipynb with your mail id

**Comment by 510617114040** [comment]
Sir i have one doubt, after did pull request my file is not showing in your
repo...

**Comment by BOOPATHI-COTPOT** [comment]
your request was not merged. please redo. your steps are correct, but you have changed another file as well. remove that and push again

**Comment by 510617114040** [comment]
Ok sir i will do,  but where i redo the file, in my repo or yours?

**Comment by BOOPATHI-COTPOT** [comment]
in your repo,
first delete your current repo, then again fork repo ,
you need start fresh

**Comment by 510617114040** [comment]
Got it, thanks!

**Comment by 510617114040** [comment]
Done as you told, check it out! :)

**Comment by 510617114040** [comment]
Hello sir,  i have a issue to fork the session 2 file from your repo to my
repo. When i fork the SESSION, all other file are download but
session_2.ipynb not showing in my repo.

**Comment by BOOPATHI-COTPOT** [comment]
try deleting your repo , then try new forking, if not working, let me know
. ill find a way

**Comment by 510617114040** [comment]
It worked.

**Comment by 510617114040** [comment]
What values for w1, w2, b for first table as i noticed 1,1,-1. is this
correct?

**Comment by BOOPATHI-COTPOT** [comment]
yes, they are correct

**Pull request closed without merging**
